
export const GET_TOTAL_ITEMS_IN_CART = 'GET_TOTAL_ITEMS_IN_CART';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const FILTER_ALL_TOYS = 'FILTER_ALL_TOYS';
export const FILTER_SOFT_TOYS = 'FILTER_SOFT_TOYS';
export const FILTER_WOODEN_TOYS = 'FILTER_WOODEN_TOYS';
export const ADD_QTY = 'ADD_QTY';
export const REMOVE_QTY = 'REMOVE_QTY';
export const USER_REG_DETAILS = 'USER_REG_DETAILS';
export const USER_LOGIN_DETAILS = 'USER_LOGIN_DETAILS';
export const USER_CHECKOUT_DETAILS = 'USER_CHECKOUT_DETAILS';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';

